# Generated by Django 4.2.11 on 2025-10-31 09:38

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField(default=1)),
                ('price', models.BigIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=models.SET(cart.models.get_unknown_product), related_name='order_items', to='products.product')),
            ],
        ),
    ]
