# Generated by Django 5.2.7 on 2025-10-31 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
