# Generated by Django 5.2.7 on 2025-11-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('products', '0003_product_public_id'),
    ]

    operations = [
    ]
