# Generated by Django 5.2.7 on 2025-11-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20251106_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category'),
        ),
    ]
